-- 코드를 작성해주세요
SELECT A.COUNT AS FISH_COUNT, A.MAX_LENGTH, A.FISH_TYPE
FROM (SELECT COUNT(*) AS COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
   FROM FISH_INFO
  GROUP BY FISH_TYPE) AS A,
(SELECT COUNT(*) AS COUNT, AVG(IF(LENGTH <= 10, 10, LENGTH)) AS AVG_LENGTH, FISH_TYPE
   FROM FISH_INFO
  GROUP BY FISH_TYPE) AS B
WHERE A.FISH_TYPE = B.FISH_TYPE
  AND B.AVG_LENGTH >= 33
ORDER BY A.FISH_TYPE
