-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT, B.MAX_LENGTH, A.FISH_TYPE
FROM FISH_INFO AS A
INNER JOIN 
(SELECT FISH_TYPE, COUNT(*) AS COUNT, AVG(IF(LENGTH <= 10, 10, LENGTH)) AS AVG_LENGTH, MAX(LENGTH) AS MAX_LENGTH
 FROM FISH_INFO
 GROUP BY FISH_TYPE
 HAVING AVG_LENGTH >= 33) AS B ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY A.FISH_TYPE
ORDER BY A.FISH_TYPE